name: Build postgres-pglite (aka Postgresql WASM)

permissions:
  pull-requests: write
  issues: write
  contents: read

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: ['REL_17_5_WASM-pglite']
  pull_request:

jobs:
  build:
    name: Build postgres-pglite (WASM Postgres)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: 'REL_17_5_WASM-pglite'

      - name: Build postgres WASI via debian 12 sdk
        working-directory: ${{ github.workspace }}
        env:
          IMG_NAME: "debian"
          DEBUG: true
          WASI: true
        run: |
          bash ./wasm-build/build-with-docker.sh

      - name: Build postgres EMSCRIPTEN via debian 12 sdk
        working-directory: ${{ github.workspace }}
        env:
          IMG_NAME: "debian"
          DEBUG: true
          WASI: false
        run: |
          bash ./wasm-build/build-with-docker.sh
